# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.runs/synth_1/riscv_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.maxThreads 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.cache/wt [current_project]
set_property parent.project_path /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_output_repo /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/hdl/riscv_wrapper.v
add_files /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.srcs/sources_1/bd/riscv/riscv.bd
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_1/bd_fe52_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_1/bd_fe52_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_2/bd_fe52_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_2/bd_fe52_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_3/bd_fe52_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_3/bd_fe52_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_7/bd_fe52_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_8/bd_fe52_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_9/bd_fe52_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_10/bd_fe52_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_11/bd_fe52_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_12/bd_fe52_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_13/bd_fe52_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_mig_7series_0_0/riscv_mig_7series_0_0/user_design/constraints/riscv_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_mig_7series_0_0/riscv_mig_7series_0_0/user_design/constraints/riscv_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_XADC_0/riscv_XADC_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_XADC_0/riscv_XADC_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_1/bd_9c60_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_1/bd_9c60_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_2/bd_9c60_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_2/bd_9c60_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_3/bd_9c60_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_3/bd_9c60_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_4/bd_9c60_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_5/bd_9c60_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_6/bd_9c60_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_7/bd_9c60_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_8/bd_9c60_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_12/bd_9c60_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_13/bd_9c60_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_14/bd_9c60_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_15/bd_9c60_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_16/bd_9c60_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_17/bd_9c60_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_21/bd_9c60_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_22/bd_9c60_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_23/bd_9c60_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_24/bd_9c60_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_25/bd_9c60_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_26/bd_9c60_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_27/bd_9c60_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_28/bd_9c60_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_29/bd_9c60_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_30/bd_9c60_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_31/bd_9c60_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/bd_0/ip/ip_32/bd_9c60_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_m_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_1/bd_9a00_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_1/bd_9a00_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_2/bd_9a00_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_2/bd_9a00_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_3/bd_9a00_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_3/bd_9a00_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_4/bd_9a00_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_5/bd_9a00_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_6/bd_9a00_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_7/bd_9a00_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_8/bd_9a00_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_9/bd_9a00_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_10/bd_9a00_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_11/bd_9a00_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_12/bd_9a00_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_13/bd_9a00_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_14/bd_9a00_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_15/bd_9a00_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_16/bd_9a00_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_17/bd_9a00_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_18/bd_9a00_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_22/bd_9a00_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_23/bd_9a00_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_24/bd_9a00_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_25/bd_9a00_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_26/bd_9a00_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_27/bd_9a00_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_28/bd_9a00_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_29/bd_9a00_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_30/bd_9a00_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_31/bd_9a00_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_32/bd_9a00_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_33/bd_9a00_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_35/bd_9a00_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_36/bd_9a00_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_37/bd_9a00_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_38/bd_9a00_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_39/bd_9a00_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_40/bd_9a00_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_42/bd_9a00_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_43/bd_9a00_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_44/bd_9a00_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_45/bd_9a00_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_46/bd_9a00_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_47/bd_9a00_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_49/bd_9a00_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_50/bd_9a00_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_51/bd_9a00_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_52/bd_9a00_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_53/bd_9a00_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/bd_0/ip/ip_54/bd_9a00_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_io_axi_s_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_clk_wiz_0_0/riscv_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_clk_wiz_0_0/riscv_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_clk_wiz_0_0/riscv_clk_wiz_0_0_late.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_clk_wiz_0_0/riscv_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/riscv_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top riscv_wrapper -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef riscv_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file riscv_wrapper_utilization_synth.rpt -pb riscv_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
