# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.srcs/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/riscv_axi_smc_1_0.xci
# IP: The module: 'riscv_axi_smc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/bd_fe52.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_0/bd_fe52_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_1/bd_fe52_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_2/bd_fe52_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_3/bd_fe52_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_4/bd_fe52_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_5/bd_fe52_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_6/bd_fe52_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_7/bd_fe52_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_8/bd_fe52_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_9/bd_fe52_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_10/bd_fe52_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_11/bd_fe52_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_12/bd_fe52_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_13/bd_fe52_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_14/bd_fe52_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_1/bd_fe52_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_1/bd_fe52_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_2/bd_fe52_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_2/bd_fe52_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_3/bd_fe52_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_3/bd_fe52_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_7/bd_fe52_s00a2s_0_ooc.xdc

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_8/bd_fe52_sarn_0_ooc.xdc

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_9/bd_fe52_srn_0_ooc.xdc

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_10/bd_fe52_sawn_0_ooc.xdc

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_11/bd_fe52_swn_0_ooc.xdc

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_12/bd_fe52_sbn_0_ooc.xdc

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_13/bd_fe52_m00s2a_0_ooc.xdc

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_axi_smc_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.srcs/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/riscv_axi_smc_1_0.xci
# IP: The module: 'riscv_axi_smc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/bd_fe52.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_0/bd_fe52_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_1/bd_fe52_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_2/bd_fe52_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_3/bd_fe52_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_4/bd_fe52_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_5/bd_fe52_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_6/bd_fe52_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_7/bd_fe52_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_8/bd_fe52_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_9/bd_fe52_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_10/bd_fe52_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_11/bd_fe52_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_12/bd_fe52_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_13/bd_fe52_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_14/bd_fe52_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_1/bd_fe52_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_1/bd_fe52_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_2/bd_fe52_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_2/bd_fe52_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_3/bd_fe52_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_3/bd_fe52_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_7/bd_fe52_s00a2s_0_ooc.xdc

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_8/bd_fe52_sarn_0_ooc.xdc

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_9/bd_fe52_srn_0_ooc.xdc

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_10/bd_fe52_sawn_0_ooc.xdc

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_11/bd_fe52_swn_0_ooc.xdc

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_12/bd_fe52_sbn_0_ooc.xdc

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/bd_0/ip/ip_13/bd_fe52_m00s2a_0_ooc.xdc

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_axi_smc_1_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_axi_smc_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
