# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.srcs/sources_1/bd/riscv/ip/riscv_XADC_0/riscv_XADC_0.xci
# IP: The module: 'riscv_XADC_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_XADC_0/riscv_XADC_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_XADC_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_XADC_0/riscv_XADC_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_XADC_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.srcs/sources_1/bd/riscv/ip/riscv_XADC_0/riscv_XADC_0.xci
# IP: The module: 'riscv_XADC_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_XADC_0/riscv_XADC_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_XADC_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /mnt/d/vivado-risc-v/workspace/rocket64b1/vivado-nexys-a7-100t-riscv/nexys-a7-100t-riscv.gen/sources_1/bd/riscv/ip/riscv_XADC_0/riscv_XADC_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_XADC_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
